/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fiber/bladerunner/chair/ribbon_chair.glb --transform 
Files: public/fiber/bladerunner/chair/ribbon_chair.glb [410.48KB] > /Users/yoshisean/Desktop/nextportfolio/ribbon_chair-transformed.glb [44.78KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RibbonChair(props) {
  const { nodes, materials } = useGLTF('fiber/bladerunner/chair/ribbon_chair-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0, 0.143, 0]}>
      <mesh geometry={nodes.bo_ribbon_chair.geometry} material={materials.wire_000000000} rotation={[Math.PI / 2, 0, 0]} scale={0.01} castShadow/>
    </group>
  )
}

useGLTF.preload('fiber/bladerunner/chair/ribbon_chair-transformed.glb')
