/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/wallace_room.glb --transform 
Files: ./public/wallace_room.glb [51.3KB] > /Users/yoshisean/Desktop/nextportfolio/wallace_room-transformed.glb [3.99KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WallaceRoom(props) {
  const { nodes, materials } = useGLTF('/fiber/bladerunner/wallace_room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SeatL.geometry} material={nodes.SeatL.material} scale={[1, 0.929, 1]} castShadow receiveShadow/>
    </group>
  )
}

useGLTF.preload('/wallace_room-transformed.glb')
