/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/wallace_room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WallaceRoom(props) {
  const { nodes, materials } = useGLTF('/fiber/bladerunner/wallace_room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SeatL.geometry} material={materials.SimpleWood} scale={[1, 0.929, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.SeatR.geometry} material={materials.SimpleWood} scale={[1, 0.929, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.Ceiling.geometry} material={materials.SimpleWood} position={[0, -0.002, 0]} receiveShadow castShadow/>
      <mesh geometry={nodes.Floor.geometry} material={materials.SimpleWood} position={[0, 0.003, -0.076]} receiveShadow castShadow/>
      <mesh geometry={nodes.floor_Front.geometry} material={materials.SimpleWood} position={[0, 0.079, 5.955]} scale={[0.6, 1, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.Back_Wall_L1.geometry} material={materials.SimpleWood} position={[0.204, 0, 0]} scale={[1.1, 1, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.Back_Wall_L2.geometry} material={materials.SimpleWood} position={[0.204, 0.009, 0]} scale={[1.1, 1, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.Back_wall_M1.geometry} material={materials.SimpleWood} receiveShadow castShadow/>
      <mesh geometry={nodes.Back_wall_M2.geometry} material={materials.SimpleWood} position={[0, 0.009, 0]} receiveShadow castShadow/>
      <mesh geometry={nodes.Back_Wall_R1.geometry} material={materials.SimpleWood} position={[-0.204, 0, 0]} scale={[1.1, 1, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.Back_Wall_R2.geometry} material={materials.SimpleWood} position={[-0.204, 0.009, 0]} scale={[1.1, 1, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.Left_Wall_Far1.geometry} material={materials.SimpleWood} position={[0, 0, -0.015]} receiveShadow castShadow/>
      <mesh geometry={nodes.Left_Wall_Near1.geometry} material={materials.SimpleWood} receiveShadow castShadow/>
      <mesh geometry={nodes.Left_Wall_Far2.geometry} material={materials.SimpleWood} position={[0, 0.009, -0.015]} receiveShadow castShadow/>
      <mesh geometry={nodes.Left_Wall_Near2.geometry} material={materials.SimpleWood} position={[0, 0.009, 0]} receiveShadow castShadow/>
      <mesh geometry={nodes.Right_Wall_Far1.geometry} material={materials.SimpleWood} position={[0, 0, -0.015]} receiveShadow castShadow/>
      <mesh geometry={nodes.Right_Wall_Near1.geometry} material={materials.SimpleWood} receiveShadow castShadow/>
      <mesh geometry={nodes.Right_Wall_Far2.geometry} material={materials.SimpleWood} position={[0, 0.009, -0.015]} receiveShadow castShadow/>
      <mesh geometry={nodes.Right_Wall_Near2.geometry} material={materials.SimpleWood} position={[0, 0.009, 0]} receiveShadow castShadow/>
      <mesh geometry={nodes.Front_Wall_Left2.geometry} material={materials.SimpleWood} position={[0.366, -1.905, 0]} scale={[1.1, 1.5, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.Front_Wall_R2.geometry} material={materials.SimpleWood} position={[-0.366, -1.905, 0]} scale={[1.1, 1.5, 1]} receiveShadow castShadow/>
      <mesh geometry={nodes.Side_Wall_L1.geometry} material={materials.SimpleWood} receiveShadow castShadow/>
      <mesh geometry={nodes.Side_Wall_L2.geometry} material={materials.SimpleWood} position={[0, 0.006, 0]} receiveShadow castShadow/>
      <mesh geometry={nodes.Side_Wall_R1.geometry} material={materials.SimpleWood} receiveShadow castShadow/>
      <mesh geometry={nodes.Side_Wall_R2.geometry} material={materials.SimpleWood} position={[0, 0.006, 0]} receiveShadow castShadow/>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.SimpleWood} position={[0, 4.308, -0.272]} rotation={[0, 0, -Math.PI / 2]} scale={[0.453, 7.234, 0.453]} receiveShadow castShadow/>
    </group>
  )
}

useGLTF.preload('/wallace_room.glb')
