/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fiber/bladerunner/wallace_room.glb --transform 
Files: public/fiber/bladerunner/wallace_room.glb [42.76MB] > /Users/yoshisean/Desktop/nextportfolio/wallace_room-transformed.glb [1.4MB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WallaceRoomOptimized(props) {
  const { nodes, materials } = useGLTF('fiber/bladerunner/wallace_room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SeatL.geometry} material={materials.SimpleWood} scale={[1, 0.929, 1]} receiveShadow castShadow/>
    </group>
  )
}

useGLTF.preload('fiber/bladerunner/wallace_room-transformed.glb')
