/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fish.glb
*/

import React, {useEffect, useMemo} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'

export function FishModel(props) {
    const group = React.useRef()
    const {nodes, materials, animations} = useGLTF('/fish.glb')
    const {actions, mixer} = useAnimations(animations, group)

    useEffect(() => {
        mixer.timeScale = 0.5
        actions.KeyAction.play()
    }, [actions]);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Fish" position={[0, 0, 0]} rotation={[Math.PI, 0, Math.PI]}>
                    <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials['Material.001']}
                          morphTargetDictionary={nodes.Mesh001.morphTargetDictionary}
                          morphTargetInfluences={nodes.Mesh001.morphTargetInfluences}/>
                    <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials['fin.001']}
                          morphTargetDictionary={nodes.Mesh001_1.morphTargetDictionary}
                          morphTargetInfluences={nodes.Mesh001_1.morphTargetInfluences}/>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/fish.glb')
