import type { Metadata } from "next";
import "./globals.css";

import {Inter, Questrial} from 'next/font/google'
const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter'
})
const questrial = Questrial({
    subsets: ['latin'],
    variable: '--font-questrial',
    weight: "400"
})
export const metadata: Metadata = {
  title: "Developer Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
            className={`${questrial.className} antialiased bg-[#FBF7ED]`}
      >
        {children}
      </body>
    </html>
  );
}
